POST http://localhost:8080/signup
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
    "login": "aina",
    "password": "aina1999"
}

###

POST http://localhost:8080/login
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "login": "aina",
  "password": "aina1997"
}

###

POST http://localhost:8080/logout
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###

GET http://localhost:8080/profile
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImFpbmEiLCJpZCI6Mn0.MdqHbXRMiuh8RsqY1KyJEihGFt7m_zXcWJYrEC_F1lDRV3r1azROwagm6Aio3eE45eWS47Z0wnmVpaRfQLHtIg

###

POST http://localhost:8080/profile
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImFpbmEiLCJpZCI6Mn0.MdqHbXRMiuh8RsqY1KyJEihGFt7m_zXcWJYrEC_F1lDRV3r1azROwagm6Aio3eE45eWS47Z0wnmVpaRfQLHtIg

{
  "password": "aina1997"
}

###

PATCH http://localhost:8080/profile
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImFpbmEiLCJpZCI6Mn0.MdqHbXRMiuh8RsqY1KyJEihGFt7m_zXcWJYrEC_F1lDRV3r1azROwagm6Aio3eE45eWS47Z0wnmVpaRfQLHtIg

{
  "fullName": "Aina Aina Aina"
}

###

POST http://localhost:8080/courses/2
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImFpbmEiLCJpZCI6Mn0.MdqHbXRMiuh8RsqY1KyJEihGFt7m_zXcWJYrEC_F1lDRV3r1azROwagm6Aio3eE45eWS47Z0wnmVpaRfQLHtIg

###